name: Update Nuclei Tags Index

# Trigger this workflow manually or on push to main
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write   # Allow the github-actions bot to push changes

jobs:
  update-tags:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout repo
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # We'll provide our token manually


    - name: Generate index
      run: |
        cd generator
        go run main.go
        mv tags-index.json ../

    # Step 3: Commit changes
    - name: Commit changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add tags-index.json
        git diff --cached --quiet || git commit -m "update nuclei tags index"

    # Step 4: Push changes using GITHUB_TOKEN
    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/mohammedgabr/altmap_updates.git main