name: Update Nuclei Tags Index

on:
  schedule:
    - cron: "0 0 * * *"   # daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Clone nuclei-templates
        run: |
          git clone https://github.com/projectdiscovery/nuclei-templates.git

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.13"

      - name: Generate index
        run: |
          cd generator
          go run main.go
          mv tags-index.json ../


      # Step 3: Commit changes
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add tags-index.json
          git diff --cached --quiet || git commit -m "update nuclei tags index"

      # Step 4: Push changes using GITHUB_TOKEN
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/mohammedgabr/altmap_updates.git main